name: build gwlbtun

on:
  push:
    branches:
      - main

jobs:
  build-gwlbtun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Boost
        uses: actions/cache@v4
        with:
          path: ~/boost
          key: boost-1.83-${{ runner.os }}
          
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libssl-dev

      - name: Install Boost 1.83.0
        run: |
            wget https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2
            tar xjf boost_1_83_0.tar.bz2
            cd boost_1_83_0
            ./bootstrap.sh
            ./b2 link=static runtime-link=static --prefix=$HOME/boost install

      - name: Build gwlbtun
        run: |
          cmake \
           -DBOOST_ROOT=$HOME/boost \
           -DBOOST_INCLUDEDIR=$HOME/boost/include \
           -DBOOST_LIBRARYDIR=$HOME/boost/lib \
           -DBoost_USE_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF .
          make

      - name: Check for built binary
        run: |
          ls -l gwlbtun
          test -f gwlbtun

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.sha }} aws-gateway-load-balancer-tunnel-handler/gwlbtun \
            --repo ${{ github.repository }} \
            --title "GWLB Tunnel Handler build ${{ github.sha }}" \
            --notes "Automated build from main @ ${{ github.sha }}"
